# Settings
name: 'Jordan Thornquest'
description: 'Hey there. Iâ€™m Jordan, an artist from from Idaho. I make power-pop & post-punk music, and often write on my blog.'
permalink: pretty
relative_permalinks: false
exclude: ["vendor", "README.md", "Gemfile", "Gemfile.lock", "config", "deploy.rb", "sample_deploy.rb"]

# Sass
sass:
  sass_dir: _scss
  style: :compressed
